# web server
nginx:
  # image: daocloud.io/nginx:latest
  build: ./nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    # app
    - ./app/src:/usr/share/nginx/html
    # nginx configs
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    # certificates
    - ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
    - ./nginx/ca/server.key/:/etc/nginx/server.key:ro
  restart: on-failure
  links:
    - fpm:__DOCKER_PHP_FPM__

# php-fpm
fpm:
  # image: daocloud.io/php:7.0.5-fpm
  build: ./php-fpm
  ports:
    - "9000"
  volumes:
    - ./app/src:/usr/share/nginx/html
    # Your php.ini
    - ./php-fpm/php.ini-production:/usr/local/etc/php/php.ini:ro
  # environment:
    # Set your APP env variables here:
    # - APP_KEY=
    # - DB_HOST=
    # - DB_DATABASE=
    # - DB_USERNAME=
    # - DB_PASSWORD=
  restart: on-failure
  links:
    - mysql:mysql

# database
mysql:
  # image: daocloud.io/mysql:latest
  build: ./mysql
  ports:
    # Allow client to access 3306
    - "3306:3306"
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  volumes:
    # NOTE: your data will be stored in ./mysql
    - ./mysql/data:/var/lib/mysql
  restart: on-failure