version: '3'

services:
  # web server
  nginx:
    # build: ./nginx
    image: hub.c.163.com/teddywen/lnmp-nginx:1.0.0
    container_name: lnmp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount www here.
      - ./app/src:/usr/share/nginx/html
      # nginx configs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      # certificates
      - ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
      - ./nginx/ca/server.key/:/etc/nginx/server.key:ro
    restart: on-failure
    networks:
      - lnmp-frontend

  # php-fpm
  fpm:
    # build: ./php-fpm
    image: hub.c.163.com/teddywen/lnmp-fpm:1.0.0
    container_name: lnmp-fpm
    # ports:
    #   - "9000"
    volumes:
      # Mount www here.
      - ./app/src:/usr/share/nginx/html
      # Your php.ini
      - ./php-fpm/php-development.ini:/usr/local/etc/php/php.ini:ro
    # environment:
      # Set your APP env variables here:
      # - APP_KEY=
      # - DB_HOST=
      # - DB_DATABASE=
      # - DB_USERNAME=
      # - DB_PASSWORD=
    restart: on-failure
    networks:
      - lnmp-frontend
      - lnmp-backend

  # database
  mysql:
    # build: ./mysql
    image: hub.c.163.com/teddywen/lnmp-mysql:1.0.0
    container_name: lnmp-mysql
    ports:
      # Allow client to access 3306
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      # NOTE: your data will be stored in ./mysql
      - ./mysql/data:/var/lib/mysql
    restart: on-failure
    networks:
      - lnmp-backend

  # cache
  memcached:
    # build: ./memcached
    image: hub.c.163.com/teddywen/lnmp-memcached:1.0.0
    container_name: lnmp-memcached
    ports:
      # Allow client to access 11211
      - "127.0.0.1:11211:11211"
    command: memcached -m 256
    restart: on-failure
    networks:
      - lnmp-backend

  # redis
  redis:
    # build: ./redis
    image: hub.c.163.com/teddywen/lnmp-redis:1.0.0
    container_name: lnmp-redis
    ports:
      # Allow client to access 6379
      - "127.0.0.1:6379:6379"
    command: redis-server --appendonly yes
    volumes:
      # NOTE: your data will be stored in ./redis
      - ./redis/data:/data
    restart: on-failure
    networks:
      - lnmp-backend

  # bash
  bash:
    # build: ./bash
    image: hub.c.163.com/teddywen/lnmp-bash:1.0.0
    container_name: lnmp-bash
    volumes:
      # Mount www here.
      - ./app/src:/usr/share/nginx/html
      - /Users/wen.xiang/vagrant_getting_started/www:/usr/share/nginx/html/intv
    restart: on-failure
    # dns:
    # Accelerate your network within container
    #   - 192.168.3.1
    networks:
      - lnmp-frontend
      - lnmp-backend
networks:
  lnmp-frontend:
  lnmp-backend:

