######
# See: https://hub.docker.com/_/nginx/
######

FROM daocloud.io/nginx:latest
LABEL com.candlesgo.image="teddywen/nginx:1.0.0" \
      com.candlesgo.author="teddywen" \
      com.candlesgo.email="763323819@qq.com" \
      com.candlesgo.description="This is a nginx image for yii2 and laravel." \
      com.candlesgo.version="1.0.0" \
      com.candlesgo.release-date="2017-05-29"