######
# See: https://hub.docker.com/_/mysql/
######

FROM daocloud.io/mysql:latest
LABEL com.candlesgo.image="teddywen/mysql:1.0.0" \
      com.candlesgo.author="teddywen" \
      com.candlesgo.email="763323819@qq.com" \
      com.candlesgo.description="This is a mysql image for yii2 and laravel." \
      com.candlesgo.version="1.0.0" \
      com.candlesgo.release-date="2017-05-29"
